# docker build -f Dockerfile-firefox-profile -t accetto/ubuntu-vnc-xfce-firefox-profile .

FROM accetto/ubuntu-vnc-xfce-firefox

ENV REFRESHED_AT 2018-03-03

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Headless Ubuntu VNC/noVNC container with Xfce desktop and Firefox with profile" \
    any.accetto.display-name="Headless Ubuntu/Xfce VNC/noVNC container with Firefox profile" \
    any.accetto.expose-services="6901:http,5901:xvnc" \
    any.accetto.tags="ubuntu, xfce, vnc, novnc, firefox, profile"

### Arguments can be provided during build
ARG VNC_BLACKLIST_TIMEOUT=0
ARG VNC_BLACKLIST_THRESHOLD=20

### Environment config
ENV \
  VNC_BLACKLIST_TIMEOUT=$VNC_BLACKLIST_TIMEOUT \
  VNC_BLACKLIST_THRESHOLD=$VNC_BLACKLIST_THRESHOLD

WORKDIR $HOME

### Preseeded Firefox profile (possibly a volume)
COPY ./src/firefox/profile/ $HOME/.mozilla/
