# docker build -f Dockerfile-firefox -t accetto/ubuntu-vnc-xfce-firefox .
# docker build -f Dockerfile-firefox --build-arg VNC_USER=joe:devs -t accetto/ubuntu-vnc-xfce-firefox:joe .

FROM accetto/ubuntu-vnc-xfce

ENV REFRESHED_AT 2018-03-03

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Headless Ubuntu VNC/noVNC container with Xfce desktop and Firefox" \
    any.accetto.display-name="Headless Ubuntu/Xfce VNC/noVNC container with Firefox" \
    any.accetto.expose-services="6901:http,5901:xvnc" \
    any.accetto.tags="ubuntu, xfce, vnc, novnc, firefox"

### Arguments can be provided during build
ARG VNC_USER=headless:headless
ARG VNC_BLACKLIST_TIMEOUT=0
ARG VNC_BLACKLIST_THRESHOLD=20

### Environment config
ENV \
  VNC_USER=$VNC_USER \
  VNC_BLACKLIST_TIMEOUT=$VNC_BLACKLIST_TIMEOUT \
  VNC_BLACKLIST_THRESHOLD=$VNC_BLACKLIST_THRESHOLD

WORKDIR $HOME

### be sure to use the root user
USER 0

### Install Firefox browser
COPY ./src/firefox/install/ $INST_SCRIPTS/
COPY ./src/firefox/Desktop/firefox.desktop $HOME/Desktop/
RUN find $INST_SCRIPTS -name '*.sh' -exec chmod a+x {} + 
RUN $INST_SCRIPTS/firefox.sh \
    && chmod +x $HOME/Desktop/firefox.desktop \
    && mkdir $HOME/Downloads \
    && mkdir $HOME/.mozilla \
    && rm $INST_SCRIPTS/*
    
COPY ./src/ubuntu/install/create_user_and_fix_permissions.sh $INST_SCRIPTS/
RUN find $INST_SCRIPTS -name '*.sh' -exec chmod a+x {} + 
RUN $INST_SCRIPTS/create_user_and_fix_permissions.sh $STARTUPDIR $HOME \
    && rm $INST_SCRIPTS/* 

### switch to the non-root user
USER $VNC_USER
