# docker build -f Dockerfile-firefox-profile -t accetto/ubuntu-vnc-xfce-firefox-profile .

FROM accetto/ubuntu-vnc-xfce-firefox

MAINTAINER accetto
ENV REFRESHED_AT 2017-12-31

LABEL vendor="accetto" \
    any.accetto.description="Headless Ubuntu VNC/noVNC container with Xfce desktop and Firefox with profile" \
    any.accetto.display-name="Headless Ubuntu/Xfce VNC/noVNC container with Firefox profile" \
    any.accetto.expose-services="6901:http,5901:xvnc" \
    any.accetto.tags="ubuntu, xfce, vnc, novnc, firefox, profile"

WORKDIR $HOME

### Preseeded Firefox profile (possibly a volume)
COPY ./src/firefox/profile/ $HOME/.mozilla/
