#!/bin/bash -xe

. ./hooks/env

if [[ -n "$BASETAG" ]] ; then

    docker build \
        -f $DOCKERFILE_PATH \
            --build-arg BASETAG="$BASETAG" \
            --build-arg ARG_REFRESHED_AT="$TODAY" \
        -t $DOCKER_REPO:$DOCKER_TAG .
else
    echo "Build request not recognized: $SOURCE_BRANCH"
fi
