#!/bin/bash -xe

. ./hooks/env

if [[ -n "${BASETAG}" ]] ; then

    docker push ${DOCKER_REPO}:${DOCKER_TAG}

    case "${DOCKER_TAG}" in
        latest)
            docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${VERSION_STICKER}
            docker push ${DOCKER_REPO}:${VERSION_STICKER}
            ;;
    esac
else
    echo "Nothing to push!"
    exit 1
fi
