#!/bin/bash -xe

. ./hooks/env

if [[ -n "${BASETAG}" ]] ; then

    docker build $@ \
        -f ${DOCKERFILE_PATH} \
            --build-arg BASETAG="${BASETAG}" \
            --build-arg ARG_REFRESHED_AT="${TODAY}" \
            --build-arg ARG_VERSION_STICKER="${VERSION_STICKER}" \
            --build-arg ARG_VCS_REF=`git rev-parse --short HEAD` \
        -t ${DOCKER_REPO}:${DOCKER_TAG} .
else
    echo "Build request not recognized: ${SOURCE_BRANCH}"
fi
