# docker build -f Dockerfile-firefox-profile_rolling -t accetto/ubuntu-vnc-xfce-firefox-profile:rolling .
# docker run -d -P -e "VNC_PW=docker" --name=rollingfox accetto/ubuntu-vnc-xfce-firefox-profile:rolling
# docker run -d -P -e "VNC_PW=docker" --user root --name=rollingfox accetto/ubuntu-vnc-xfce-firefox-profile:rolling

FROM accetto/ubuntu-vnc-xfce-firefox:rolling

ENV REFRESHED_AT 2018-04-24

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Headless Ubuntu VNC/noVNC container with Xfce desktop and Firefox with profile" \
    any.accetto.display-name="Headless Ubuntu/Xfce VNC/noVNC container with Firefox profile" \
    any.accetto.expose-services="6901:http,5901:xvnc" \
    any.accetto.tags="ubuntu, xfce, vnc, novnc, firefox, profile"

### Arguments can be provided during build
ARG VNC_BLACKLIST_TIMEOUT=0
ARG VNC_BLACKLIST_THRESHOLD=20

SHELL ["/bin/bash", "-c"]

### Environment config
ENV \
  VNC_BLACKLIST_TIMEOUT=$VNC_BLACKLIST_TIMEOUT \
  VNC_BLACKLIST_THRESHOLD=$VNC_BLACKLIST_THRESHOLD

WORKDIR $HOME

### Be sure to use the root user
USER 0

### Copy the pre-configured Firefox profile
COPY ./src/firefox/profile/ $HOME/.mozilla/

### Change owner
RUN chown -R $VNC_USER $HOME/.mozilla

### Switch to the non-root user
USER $VNC_USER
