# docker build -f Dockerfile-firefox-preferences -t accetto/ubuntu-vnc-xfce-firefox-preferences .
# docker run -d -P -e "VNC_PW=docker" --name=firefox accetto/ubuntu-vnc-xfce-firefox-preferences
# docker run -d -P -e "VNC_PW=docker" --user root --name=rootfox accetto/ubuntu-vnc-xfce-firefox-preferences

FROM accetto/ubuntu-vnc-xfce-firefox

ENV REFRESHED_AT 2018-04-30

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Headless Ubuntu VNC/noVNC container with Xfce desktop and Firefox with profile" \
    any.accetto.display-name="Headless Ubuntu/Xfce VNC/noVNC container with Firefox profile" \
    any.accetto.expose-services="6901:http,5901:xvnc" \
    any.accetto.tags="ubuntu, xfce, vnc, novnc, firefox, profile"

### Arguments can be provided during build
ARG VNC_BLACKLIST_THRESHOLD=20
ARG VNC_BLACKLIST_TIMEOUT=0

SHELL ["/bin/bash", "-c"]dim

### Environment config
ENV \
  VNC_BLACKLIST_TIMEOUT=$VNC_BLACKLIST_TIMEOUT \
  VNC_BLACKLIST_THRESHOLD=$VNC_BLACKLIST_THRESHOLD \
  INST_SCRIPTS=./src/firefox/install

WORKDIR $HOME

### Be sure to use the root user
USER 0

### Put all the user preferences you want to force administratively into the file 'all-accetto.js'.
### The preferences will be forced for each session in all profiles.
### The VNC user ('headles:headless' by default) will get permissions to modify the file.
### The file is currently empty. The fix for issue #2 has been moved to 'user.js'.
COPY $INST_SCRIPTS/all-accetto.js /usr/lib/firefox/browser/defaults/preferences/

### Copy the file with default user preferences.
### The preferences will be forced for each session, but only in the profile containing the file.
### Make also a backup copy of the file (/headless/.mozilla/firefox/user.js.txt).
### The VNC user ('headles:headless' by default) will get permissions to modify or delete the file.
COPY $INST_SCRIPTS/user.js $HOME/.mozilla/firefox/profile0.default
COPY $INST_SCRIPTS/user.js $HOME/firefox.backup/profile0.default/user.js

### Fix permissions
RUN chgrp $(id -g $(echo "$VNC_USER" | cut -d : -f 1)) /usr/lib/firefox/browser/defaults/preferences/all-accetto.js \
    && chmod 664 /usr/lib/firefox/browser/defaults/preferences/all-accetto.js \
    && chown $VNC_USER $HOME/.mozilla/firefox/profile0.default/user.js \
    && chmod 600 $HOME/.mozilla/firefox/profile0.default/user.js \
    && chown $VNC_USER $HOME/firefox.backup/profile0.default/user.js \
    && chmod 600 $HOME/firefox.backup/profile0.default/user.js

### Switch to the non-root user
USER $VNC_USER
